services:
  reverse-proxy:
    image: ilyamatsuev/reverse-proxy
    container_name: reverse-proxy
    build: .
    restart: unless-stopped
    tty: true
    volumes:
      - ./config:/app/config
      - ./ssl:/app/ssl
    environment:
      - PORT_HTTP=80
      - PORT_HTTPS=443
      - NODE_ENV=prod
    network_mode: host

  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    env_file: ./config/pihole/.env.pihole.prod
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8000:8080/tcp"
      - "8443:8443/tcp"
    volumes:
      - ./config/pihole/data:/etc/pihole
      - ./config/pihole/dnsmasq.d:/etc/dnsmasq.d
