services:
  reverse-proxy:
    image: ilyamatsuev/reverse-proxy
    container_name: reverse-proxy
    network_mode: host
    build: .
    restart: always
    ports:
      - "443:443"
    expose:
      - "443"
    volumes:
      - ./config:/app/config
      - ./ssl:/app/ssl
    environment:
      - NODE_ENV=prod
