services:
  reverse-proxy:
    image: ilyamatsuev/reverse-proxy
    container_name: reverse-proxy
    build: .
    restart: always
    tty: true
    volumes:
      - ./config:/app/config
      - ./ssl:/app/ssl
    environment:
      - PORT_HTTP=80
      - PORT_HTTPS=443
      - NODE_ENV=prod
    network_mode: host
